# Generated by Django 5.0.2 on 2024-03-20 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('buss_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254, null=True)),
                ('buss_shortcode', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('consumer_key', models.CharField(max_length=254, null=True)),
                ('secret_key', models.CharField(max_length=254, unique=True)),
                ('passkey', models.CharField(default='none', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('l_name', models.CharField(max_length=254)),
                ('card_no', models.CharField(max_length=254, null=True)),
                ('expiry', models.CharField(max_length=254, null=True)),
                ('cvc', models.CharField(max_length=254, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalapp.seller')),
            ],
        ),
    ]
