# Generated by Django 5.0.1 on 2024-01-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=254)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('buss_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('buss_shortcode', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('consumer_key', models.CharField(max_length=254, null=True)),
                ('secret_key', models.CharField(max_length=254, unique=True)),
            ],
        ),
    ]
