# Generated by Django 5.0.2 on 2024-03-20 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('f_name', models.CharField(max_length=254)),
                ('l_name', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('card_no', models.CharField(max_length=254, null=True)),
                ('expiry', models.CharField(max_length=254, null=True)),
                ('cvc', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('buss_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=254, null=True)),
                ('registration_number', models.CharField(max_length=254, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('buss_shortcode', models.CharField(max_length=254, null=True)),
                ('password', models.CharField(max_length=254)),
                ('consumer_key', models.CharField(max_length=254, null=True)),
                ('secret_key', models.CharField(max_length=254, null=True)),
                ('passkey', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registration_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalapp.seller')),
            ],
        ),
    ]
