# Generated by Django 5.0.2 on 2024-03-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='0', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
