# Generated by Django 5.0.1 on 2024-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='passkey',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
