# Generated by Django 5.0.2 on 2024-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0002_seller_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
