# Generated by Django 5.0.2 on 2024-03-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0002_seller_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_request',
            name='status',
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller_record',
            name='time',
            field=models.DateField(),
        ),
    ]
