# Generated by Django 5.0.2 on 2024-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0003_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='buss_shortcode',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
