# Generated by Django 5.0.2 on 2024-03-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0004_customer_email_alter_customer_f_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucesstrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
